### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by godpow** [CampAsAChamp/MS-Paint-Automation#1]
Hello, I'm really enjoying the program so far! I was wondering if it would be possible to make a future where it would grab a row of colors it needs to fill those in then get another row of colors. I think it would look pretty neat!

**Comment by godpow** [comment]
Also, it seems like the fastest you could make it go without messing the image up is to put the speed at 0.01 but for some images that could take an hour plus. Would it be possible to add threading or some way for it to process 0 speed without it messing the image up?

**Comment by godpow** [comment]
I also think it would be interesting to see if making an ms paint automation tool in c# using https://github.com/FlaUI/FlaUI or something similar would be possible!

**Comment by CampAsAChamp** [comment]
Hey! Thank you for the feature requests and the feedback on this!

Unfortunately I'm not really working on this project anymore, but wanted to update it with a nicer readme in case others come across the project and wanted to use it or add on to it. 

The code isn't great and definitely needs improvements but it's not something I'm gonna be working on in the future. Feel free to fork to work on this repo, or fork it and make your own.

**Comment by CampAsAChamp** [comment]
Closing this issue because this project is no longer being maintained by me.
